name: Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  deploy:
    secrets: inherit
    uses: ./.github/workflows/ftp.yml
    with:
      environmentName: ${{inputs.environmentName}}
