name: Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - if: inputs.environmentName == 'Development'
        uses: ./ftp.yml
        with:
          server_ip: ${{secrets.SERVER_IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          localpath: ${{secrets.LOCALPATH}}
          remotepath: ${{secrets.REMOTEPATH}}
          environmentName: ${{inputs.environmentName}}
