name: FTP to server

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  ftp:
    runs-on: self-hosted
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: ${{secrets.LOCALPATH}}

      - name: scp all files and folders
        run: sudo cp -r ${{secrets.LOCALPATH}} ${{secrets.REMOTEPATH}}
