name: Publish Package

on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2.2.1

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: "6.x"

      - name: Create the package
        run: nuget pack Base.Api.nuspec -NoDefaultExcludes

      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
